
name: CICD

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 

      - name: Build docker image
        run: docker build -t yj80669/aws-docker-gitaction-test .

      - name: taging
        run: docker tag yj80669/aws-docker-gitaction-test ${{ secrets.DOCKER_USERNAME }}/aws-docker-gitaction-test:latest

      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/aws-docker-gitaction-test:latest
    
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            port: ${{ secrets.PORT }}
            # 도커 작업
            script: |
              docker pull ${{ secrets.DOCKER_USERNAME }}/aws-docker-gitaction-test:latest
              docker stop $(docker ps -a -q)
              docker run -d --log-driver=syslog -p 8000:3000 ${{ secrets.DOCKER_USERNAME }}/aws-docker-gitaction-test:latest
              docker rm $(docker ps --filter 'status=exited' -a -q)
              docker image prune -a -f
